recipes = [
    {
        'directions': [
            "preheat oven to 350.",
            "grease a 13 x 9 x 2 inch baking pan.",
            "place 1 sheet of the dough on a work surface.",
            "brush with melted butter.",
            "top with another sheet of dough and brush with butter. repeat with 3 more sheets of dough, brushing each sheet with butter between each layer.",
            "combine walnuts and cinnamon in a small bowl.",
            "sprinkle half of the walnut mixture over the dough.",
            "repeat with the remaining dough and walnut mixture.",
            "starting at the long side, roll up the dough into a log.",
            "cut the log into 1 inch slices.",
            "arrange the slices, cut side down, in the prepared baking dish.",
            "bake until golden brown, about 30 minutes.",
            "meanwhile, bring water and honey to a boil.",
            "remove from heat and stir in chocolate until melted.",
            "pour over the cooled strudel.",
            "serve warm or at room temperature.",
            "makes 12 servings.",
        ],
        'ingredients': [
            "1 lb. phyllo dough, thawed 1 lb. phyllo dough, thawed",
            "1 c. unsalted butter, melted",
            "2 c chopped walnuts",
            "1/2 tsp. cinnamon",
            "1 1/2 c water",
            "3/4 c honey",
            "1/4 c melted chocolate",
        ],
        'title': 'Baklava'
    },
    {
        'directions': [
            "in a large skillet, heat oil to 375.",
            "season chops on both sides with salt and pepper.",
            "dredge chops in flour, shaking off excess.",
            "dip chops into eggs, then coat with breadcrumbs.",
            "fry chops until golden brown, about 3 minutes per side.",
            "transfer to a platter and keep warm.",
            "pour off all but 1 tablespoon of fat from skillet.",
            "add gravy and cook over medium heat, stirring occasionally, until thickened, about 5 minutes.",
            "spoon gravy over chops and sprinkle with parsley.",
            "makes 4 servings.",
        ],
        'ingredients': [
            "1 lb beef, cubed",
            "2 tablespoons oil",
            "1 large onion, chopped",
            "2 medium tomatoes, peeled and chopped",
            "1 teaspoon turmeric powder",
            "2 limes, juice of",
            "1 cup water",
            "salt",
            "pepper",
            "1 15 ounce can red beans, drained and rinsed",
            "1 tablespoon dried herb",
        ],
        'title': 'Beef And Red Beans'
    },
    {
        'directions': [
            "heat the oil in a large saucepan.",
            "add the onion and saute until golden brown.",
            "stir in the tomatoes, turmeric powder, lime juice, water, salt and pepper.",
            "bring to a boil.",
            "reduce the heat and simmer for 10 minutes.",
            "mix in the beef and beans.",
            "cover and cook over low heat for 30 minutes or until the beef is tender.",
            "garnish with the dried herbs.",
        ],
        'ingredients': [
            "oil for frying",
            "4 6 oz. boneless pork loin chops",
            "salt",
            "pepper",
            "1/2 c. flour",
            "2 eggs, lightly beaten",
            "2 tbsp. dry breadcrumbs",
            "gravy",
            "chopped parsley",
        ],
        'title': 'Breaded Pork Chops With Gravy'
    }
]
